name: Build and Push Docker Image

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker image tags (always lowercase)
        id: docker_tags
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          IMAGE_LC=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          TAGS=""
          if [[ "${GITHUB_EVENT_NAME}" == "push" && "${GITHUB_REF}" == "refs/heads/main" ]]; then
            TAGS="${IMAGE_LC}:latest"
          elif [[ "${GITHUB_EVENT_NAME}" == "push" && "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
            TAGS="${IMAGE_LC}:${TAG}"
          else
            TAGS="${IMAGE_LC}:pr-${GITHUB_SHA::7}"
          fi
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image (AMD64)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_tags.outputs.tags }}
